version: '3'
services:
    gtrends:
        container_name: gtrends
        ports:
            - '8888:8888'
        volumes:
            - C:\Users\SOMD7W\Desktop\DL_Projects\trend_analyzer:/home/jovyan/work
        image: chezhipower/quant_projects:trends